# Page settings
baseurl = "localhost:1313"
title = "Luxe Smiles Dental Center"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]

  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Daryl Galvez"
  description = "Static website for Luxe Smiles Dental Center"
  email = "daryl.kevin.24@gmail.com"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = "Luxe Smiles Dental Center"
    home = "Home"
    work = "Work"
    testimonials = "Testimonials"
    services = "Services"
    about = "Our Dentists"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

  # Hero section
  [params.hero]
    title = "Imparting beautiful, healthy smiles to you."
    subtitle = "Our clinic offers a wide range of services that prioritizes your health and safety. We achieve this through proper and accurate diagnosis. We encourage our patients to have an active participation and interaction in our treatments which fosters a comfortable and friendly environment."

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Latest Techniques"
    description = "Our clinic is equipped with state-of-the-art equipment and technology in order for us to offer you the best and most efficient treatment that you deserve."
    # url = "#"
    # button = "Get In Touch"
    icon = "icon-diamond"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Specialized Practice"
    description = "Our dentists trained under experts in their own respective fields, most notable of which are dental surgery, dental implants, periodontal treatment, and pediatric dentistry."
    # url = "#"
    # button = "Click Me"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Certified Experts"
    description = "Our dentists are experienced practicioners who can handle complicated cases. They are actively and continuously improving and educating themselves on different fields of dentistry."
    # url = "#"
    # button = "Why us?"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = true
    title = "Work"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Project 1"
      subtitle = "Branding"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Project 2"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Project 5"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"




  # Services section
  [params.services]
    enable = true
    title = "Services"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.services.item]]
      title = "Brand &amp; Strategy"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Web &amp; Interface"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-layers2"
    [[params.services.item]]
      title = "Photo &amp; Video"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-video2"

      [[params.services.item]]
      title = "CMS &amp; eCommerce"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = true
    title = "Meet our Dentists!"
    description = "Our team consists of dedicated, experienced, and well-trained dentists each specializing in different fields in Dentistry. You can be sure that we got you covered whatever your needs may be!"

    [[params.about.item]]
      name = "Dr. Keneshia Tingson"
      position = "Dental Surgeon, Dental Implant, Esthetic Dentist, Periodontal Treatment"
      description = "Dr. Keneshia Tingson received special training in dental surgery and hospital dentistry. She was mentored by different experts in the field of implant dentistry. She is adept at managing periodontal problems and specializes in dental surgery procedures."
      img = "fbken.jpg"
      alt = "Keneshia Tingson"
      social = [
        # ["icon-twitter", "#"],
        # ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Dr. Louielyn Panganiban"
      position = "Dental Surgeon, TMJD Treatment, Prosthodontics, Periodontal Treatment, Orthodontics"
      description = "Dr. Louielyn Panganiban honed her skills in several fields, namely dental surgery, TMJD Treatment and periodontal treatment. She ranked 7th in PRC Dental Board Examination. She is well versed in proper diagnoses and in viewing dental concerns wholistically in order to provide the best possible dental care."
      img = "fblou1.jpg"
      alt = "Person2"
      social = [
        # ["icon-twitter", "#"],
        # ["icon-facebook", "#"],
        # ["icon-github", "#"]
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Dr. Sarah Panganiban"
      position = "Pediatric Dentistry and Orthodontics"
      description = "Dr. Sarah Panganiban specializes in pediatric dental care. She has proper training in management of pediatric patients including healthy, medically compromized, behaviorally challenging patients and various other special conditions."
      img = "fbsarah1.jpg"
      alt = "Person3"
      social = [
        # ["icon-twitter", "#"],
        # ["icon-facebook", "#"],
        # ["icon-dribbble", "#"]
        ["icon-linkedin", "#"]
      ]

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Adult patients served"
      icon = "icon-people"
      from = 0
      to = 2543
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Successful odontects"
      icon = "icon-heart"
      from = 0
      to = 508
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Successful implants procedure"
      icon = "icon-wrench"
      from = 0
      to = 30
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Pediatric patients served"
      icon = "icon-people"
      from = 0
      to = 152
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Get in touch"
    description = "Give us a call! Send us a message! You can also visit our clinic! You can be sure that quality dental care is always available to you."

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Room B303 Coral Center Southwoods City, Bin√£n, Laguna, Philippines 4024"],
        ["icon-phone", "(02) 330 02 50", "0910 450 8110", "0975 378 3790"],
        ["icon-phone", "0910 450 8110"],
        ["icon-phone", "0975 378 3790"],
        ["icon-envelope", "luxesmilesdc@gmail.com"],
        # ["icon-globe", '<a href="http://freehtml5.co/" target="_blank">freehtml5.co</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Luxe Smiles Dental Center. This site is made using Hugo and themed with hugo-elate-theme.'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"]
      ]
